name: Forum Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, comment-service]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          cd ${{ matrix.service }}
          npm install # Kriteria 6a

      - name: Run Unit Tests
        run: |
          cd ${{ matrix.service }}
          npm run test --if-present # Kriteria 6b

      - name: Build Application
        run: |
          cd ${{ matrix.service }}
          npm run build # Kriteria 6c

  frontend-laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, dom, fileinfo, mysql

      - name: Install Composer Dependencies
        run: |
          cd frontend-laravel
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env file
        run: |
          cd frontend-laravel
          cp .env.example .env

      - name: Generate App Key
        run: |
          cd frontend-laravel
          php artisan key:generate

  docker-check:
    runs-on: ubuntu-latest
    needs: [backend-services, frontend-laravel]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Compose Images
        run: docker-compose build
